import { useAtom } from "jotai"
import { tokenAtom, userAtom } from "../state/atoms"
import { useAuthenticationApi } from "../api/authentication"
import { useMutation, useQuery } from "@tanstack/react-query"
import { TokenType } from "../types/user"
import { RESET } from "jotai/utils"
import { useUserApi } from "../api/user"
