/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as CreateImport } from './routes/create'
import { Route as CardsImport } from './routes/cards'
import { Route as PathlessImport } from './routes/_pathless'
import { Route as IndexImport } from './routes/index'
import { Route as TemplatesIndexImport } from './routes/templates/index'
import { Route as TemplatesCreateImport } from './routes/templates/create'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateRoute = CreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const CardsRoute = CardsImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRoute,
} as any)

const PathlessRoute = PathlessImport.update({
  id: '/_pathless',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesIndexRoute = TemplatesIndexImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRoute,
} as any)

const TemplatesCreateRoute = TemplatesCreateImport.update({
  id: '/templates/create',
  path: '/templates/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_pathless': {
      id: '/_pathless'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessImport
      parentRoute: typeof rootRoute
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/templates/create': {
      id: '/templates/create'
      path: '/templates/create'
      fullPath: '/templates/create'
      preLoaderRoute: typeof TemplatesCreateImport
      parentRoute: typeof rootRoute
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PathlessRoute
  '/cards': typeof CardsRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates/create': typeof TemplatesCreateRoute
  '/templates': typeof TemplatesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PathlessRoute
  '/cards': typeof CardsRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates/create': typeof TemplatesCreateRoute
  '/templates': typeof TemplatesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_pathless': typeof PathlessRoute
  '/cards': typeof CardsRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates/create': typeof TemplatesCreateRoute
  '/templates/': typeof TemplatesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/cards'
    | '/create'
    | '/login'
    | '/register'
    | '/templates/create'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/cards'
    | '/create'
    | '/login'
    | '/register'
    | '/templates/create'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_pathless'
    | '/cards'
    | '/create'
    | '/login'
    | '/register'
    | '/templates/create'
    | '/templates/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessRoute: typeof PathlessRoute
  CardsRoute: typeof CardsRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TemplatesCreateRoute: typeof TemplatesCreateRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessRoute: PathlessRoute,
  CardsRoute: CardsRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TemplatesCreateRoute: TemplatesCreateRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_pathless",
        "/cards",
        "/create",
        "/login",
        "/register",
        "/templates/create",
        "/templates/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_pathless": {
      "filePath": "_pathless.tsx"
    },
    "/cards": {
      "filePath": "cards.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/templates/create": {
      "filePath": "templates/create.tsx"
    },
    "/templates/": {
      "filePath": "templates/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
